name: Release
on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string
      network:
        required: true
        type: string
      signing:
        required: false
        type: string
      build_workflow:
        required: true
        type: string
jobs:
  release:
    runs-on: ubuntu-20.04
    environment:
      name: ${{ needs.extract.outputs.network }}
    strategy:
      matrix:
        targetPlatform:
          - Windows
          - macOS
          - Linux
    steps:
      - uses: actions/checkout@v3

      - name: release
        uses: planetarium/9c-toolbelt@update-player-verison
        with:
          COMMAND_LIST: "release|player|${{ github.sha }}|${{ inputs.version }}|${{ inputs.network }}|${{ matrix.targetPlatform }}|${{ inputs.signing }}|--slack-channel=${{ secrets.SLACK_CHANNEL }}|--run-id=${{ inputs.build_workflow }}"
          ENV: production
          GITHUB_TOKEN: ${{ secrets.P_GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
          ESIGNER_CREDENTIAL_ID: ${{ secrets.ESIGNER_CREDENTIAL_ID }}
          ESIGNER_USERNAME: ${{ secrets.ESIGNER_USERNAME }}
          ESIGNER_PASSWORD: ${{ secrets.ESIGNER_PASSWORD }}
          ESIGNER_TOTP_SECRET: ${{ secrets.ESIGNER_TOTP_SECRET }}

  update-latest-metadata:
    runs-on: ubuntu-20.04
    needs: release
    environment:
      name: ${{ inputs.network }}
    steps:
      - name: update-latest-metadata
        uses: planetarium/9c-toolbelt@update-player-verison
        with:
          COMMAND_LIST: "release|update-latest|${{ github.sha }}|${{ inputs.version }}|${{ inputs.network }}|--slack-channel=${{ secrets.SLACK_CHANNEL }}"
          ENV: production
          GITHUB_TOKEN: ${{ secrets.P_GITHUB_TOKEN }}
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          SLACK_TOKEN: ${{ secrets.SLACK_TOKEN }}
